name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.13.1
        uses: actions/setup-node@v2
        with:
          node-version: v12.13.1
      - run: npm ci
      - run: npm test